pipeline {
  agent any
  stages {  
    
  
   
   
     stage('Jacoco Coverage Report') {
            steps{
                    jacoco()
        }
    }
      
    stage('SonarQube'){
        steps{
                bat label: '', script: '''mvn sonar:sonar \
                -Dsonar.host.url=http://localhost:9000 \
                -Dsonar.login=4d872fd2d7656ee3bfedabb7925c8c5eea4173e4'''
            }
           }     
  
  }
}